import type { MentalModel } from "./types";

/**
 * The v1 curated repository (§5.1–5.4): quality over volume, every entry attributed,
 * summarized in original language rather than reproduced from source text.
 */
export const MODELS: MentalModel[] = [
  // ───────────────────────── Psychology & judgment ─────────────────────────
  {
    id: "loss-aversion",
    name: "Loss Aversion",
    aliases: ["prospect theory"],
    domain: "psychology",
    originator: "Daniel Kahneman & Amos Tversky",
    primarySource: "Prospect theory (1979)",
    oneLine: "A loss of a given size hurts roughly twice as much as an equivalent gain pleases.",
    whenToUse: [
      "One option is framed as giving something up, even if the underlying numbers are close.",
      "You notice you're protecting a status quo more than evaluating it.",
    ],
    whenItMisleads: [
      "Naming the bias doesn't neutralise it — sometimes the aversion is correct because the loss really is the bigger risk.",
    ],
    decisionTypes: ["binary", "risk", "values-conflict"],
    stakesFit: ["medium", "high"],
    relatedModels: ["regret-minimization"],
    contradicts: ["expected-value"],
    visualTemplate: "narrative",
    keywords: ["give up", "lose", "keep", "afraid", "risk", "safe", "stay"],
  },
  {
    id: "sunk-cost-fallacy",
    name: "Sunk Cost Fallacy",
    aliases: ["sunk cost"],
    domain: "psychology",
    originator: "Behavioral economics; formalised in decision theory",
    primarySource: "Arkes & Blumer (1985)",
    oneLine: "Money, time, or effort already spent is gone either way — it shouldn't weigh on what you do next.",
    whenToUse: [
      "You catch yourself justifying a choice by how much you've already put in.",
      "The honest question is what you'd choose today, starting from zero.",
    ],
    whenItMisleads: [
      "Past investment can be a legitimate signal about fit or competence, not always a trap — don't use this to dismiss real information.",
    ],
    decisionTypes: ["binary", "timing"],
    relatedModels: ["opportunity-cost"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["invested", "years", "already spent", "quit", "waste", "committed"],
  },
  {
    id: "anchoring-bias",
    name: "Anchoring Bias",
    aliases: ["anchoring-and-adjustment"],
    domain: "psychology",
    originator: "Daniel Kahneman & Amos Tversky",
    primarySource: "Judgment under Uncertainty (1974)",
    oneLine: "The first number or option you're shown quietly sets the scale for everything after it.",
    whenToUse: [
      "There's an initial offer, estimate, or precedent in play before you've reasoned independently.",
      "Useful for checking whether your gut number is really yours.",
    ],
    whenItMisleads: [
      "Deliberately ignoring a genuinely informative first data point just to avoid anchoring is its own error.",
    ],
    decisionTypes: ["negotiation", "resource-allocation", "binary"],
    relatedModels: ["anchoring-in-negotiation"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["offer", "asking price", "first number", "quote", "estimate"],
  },
  {
    id: "present-bias",
    name: "Present Bias",
    aliases: ["hyperbolic discounting"],
    domain: "psychology",
    originator: "George Ainslie; formalised by David Laibson",
    primarySource: "Hyperbolic discounting literature",
    oneLine: "Near-term costs and rewards are weighted far more heavily than ones the same size further out.",
    whenToUse: [
      "One option pays off soon and the other pays off later — check if that timing alone is doing the persuading.",
      "Useful whenever 'now' and 'later' options are being compared head-to-head.",
    ],
    whenItMisleads: [
      "Sometimes the near-term option really is better; don't discount immediacy just because it's a known bias.",
    ],
    decisionTypes: ["timing", "binary"],
    relatedModels: ["ten-ten-ten-rule"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["now", "later", "soon", "wait", "deadline", "immediate"],
  },
  {
    id: "status-quo-bias",
    name: "Status Quo Bias",
    aliases: ["default effect"],
    domain: "psychology",
    originator: "William Samuelson & Richard Zeckhauser",
    primarySource: "Status Quo Bias in Decision Making (1988)",
    oneLine: "Staying put feels like the safe, neutral choice even when it's an active decision with its own cost.",
    whenToUse: [
      "One path is literally 'do nothing' or 'keep things as they are.'",
      "Ask whether you'd choose the status quo if you were starting fresh today.",
    ],
    whenItMisleads: [
      "Inertia sometimes reflects real, hard-won stability — don't treat 'stay' as automatically the biased option.",
    ],
    decisionTypes: ["binary", "timing"],
    relatedModels: ["opportunity-cost", "two-way-vs-one-way-door"],
    contradicts: ["opportunity-cost"],
    visualTemplate: "narrative",
    keywords: ["stay", "keep things", "as they are", "change", "current"],
  },
  {
    id: "paradox-of-choice",
    name: "Paradox of Choice",
    aliases: ["choice overload"],
    domain: "psychology",
    originator: "Barry Schwartz",
    primarySource: "The Paradox of Choice (2004)",
    oneLine: "Past a point, more options lower satisfaction and raise regret rather than improving the decision.",
    whenToUse: [
      "You're facing more than three or four live options and feel stuck rather than empowered.",
      "Useful for deciding to prune the option set before comparing what's left.",
    ],
    whenItMisleads: [
      "Cutting options too early can remove a genuinely better path just to reduce discomfort.",
    ],
    decisionTypes: ["multi-option"],
    relatedModels: ["satisficing-vs-maximizing"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["many options", "several", "which one", "overwhelmed", "too many"],
  },
  {
    id: "confirmation-bias",
    name: "Confirmation Bias",
    aliases: [],
    domain: "psychology",
    originator: "Peter Wason",
    primarySource: "On the failure to eliminate hypotheses (1960)",
    oneLine: "We notice and weigh evidence that supports the choice we already lean toward, and discount the rest.",
    whenToUse: [
      "You realise you've already picked a favourite and are now collecting reasons for it.",
      "Useful as a check right before you finalise a decision you feel strongly about.",
    ],
    whenItMisleads: [
      "A strong prior isn't automatically wrong — don't manufacture false doubt just to seem balanced.",
    ],
    decisionTypes: ["binary", "values-conflict"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["sure", "convinced", "obviously", "already decided", "feel strongly"],
  },

  // ───────────────────────── Economics & value ─────────────────────────
  {
    id: "opportunity-cost",
    name: "Opportunity Cost",
    aliases: [],
    domain: "economics",
    originator: "Frédéric Bastiat",
    primarySource: "That Which Is Seen and That Which Is Not Seen (1850)",
    oneLine: "The real cost of any choice is the best alternative you gave up to make it.",
    whenToUse: [
      "Whenever picking one option quietly forecloses another worth naming explicitly.",
      "Especially useful when a choice looks free just because no cash changes hands.",
    ],
    whenItMisleads: [
      "It assumes the foregone alternative was actually available and realistic — don't cost out a fantasy option.",
    ],
    decisionTypes: ["binary", "resource-allocation", "timing"],
    relatedModels: ["comparative-advantage"],
    contradicts: ["status-quo-bias"],
    visualTemplate: "narrative",
    keywords: ["give up", "alternative", "instead", "trade-off", "foregone"],
  },
  {
    id: "circle-of-competence",
    name: "Circle of Competence",
    aliases: ["domain expertise boundary"],
    domain: "economics",
    originator: "Warren Buffett & Charlie Munger",
    primarySource: "Berkshire Hathaway shareholder letters",
    oneLine: "Know the boundary of what you actually understand well, and weight your confidence accordingly.",
    whenToUse: [
      "The decision depends on a domain you have real, earned experience in, or clearly don't.",
      "Useful for calibrating how much to trust your own read versus seeking outside judgment.",
    ],
    whenItMisleads: [
      "It can become an excuse to avoid ever stretching into adjacent, learnable territory.",
    ],
    decisionTypes: ["binary", "risk", "multi-option"],
    relatedModels: ["base-rates"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["expert", "know about", "unfamiliar", "new industry", "experience"],
  },
  {
    id: "margin-of-safety",
    name: "Margin of Safety",
    aliases: [],
    domain: "economics",
    originator: "Benjamin Graham",
    primarySource: "The Intelligent Investor (1949)",
    oneLine: "Build in enough buffer that you're still fine even if your estimates turn out to be too optimistic.",
    whenToUse: [
      "Your plan only works if your best-case numbers hold — that's a sign you need more cushion.",
      "Useful before committing to anything with a hard floor if things go wrong.",
    ],
    whenItMisleads: [
      "Excess caution can mean never acting at all — a margin of safety isn't a reason to demand certainty.",
    ],
    decisionTypes: ["risk", "resource-allocation"],
    stakesFit: ["medium", "high"],
    relatedModels: ["black-swan-tail-risk"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["buffer", "cushion", "worst case", "afford", "downside"],
  },
  {
    id: "diminishing-returns",
    name: "Diminishing Returns",
    aliases: ["law of diminishing marginal returns"],
    domain: "economics",
    originator: "Classical economics; formalised by Alfred Marshall",
    primarySource: "Principles of Economics (1890)",
    oneLine: "Each additional unit of effort or investment tends to produce less extra benefit than the one before it.",
    whenToUse: [
      "You're deciding whether to push further on something you're already deep into.",
      "Useful for spotting when 'more' has stopped paying for itself.",
    ],
    whenItMisleads: [
      "Some efforts have a threshold effect where the payoff jumps late — don't assume every curve flattens smoothly.",
    ],
    decisionTypes: ["resource-allocation", "timing"],
    relatedModels: ["theory-of-constraints"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["more time", "more money", "keep pushing", "extra", "worth it"],
  },
  {
    id: "comparative-advantage",
    name: "Comparative Advantage",
    aliases: [],
    domain: "economics",
    originator: "David Ricardo",
    primarySource: "On the Principles of Political Economy and Taxation (1817)",
    oneLine: "Specialise where your relative edge is largest, even if you're decent at everything on the table.",
    whenToUse: [
      "You're allocating your own time or a team's effort across multiple things you could all do reasonably well.",
      "Useful for deciding what to hand off rather than what you could technically do yourself.",
    ],
    whenItMisleads: [
      "It assumes trade or delegation is actually available — sometimes you really are the only option.",
    ],
    decisionTypes: ["resource-allocation", "multi-option"],
    relatedModels: ["opportunity-cost"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["delegate", "outsource", "focus on", "good at", "hand off"],
  },
  {
    id: "switching-costs",
    name: "Switching Costs",
    aliases: [],
    domain: "economics",
    originator: "Industrial organisation economics",
    primarySource: "Klemperer, Markets with Consumer Switching Costs (1987)",
    oneLine: "The friction of moving from one option to another is a real cost, separate from the option's own merits.",
    whenToUse: [
      "An incumbent choice looks worse on paper but changing carries its own setup cost or relearning curve.",
      "Useful for separating 'is this better' from 'is switching worth it.'",
    ],
    whenItMisleads: [
      "Switching costs are usually temporary and one-time — don't let them justify staying somewhere with an ongoing, compounding downside.",
    ],
    decisionTypes: ["binary", "timing"],
    relatedModels: ["status-quo-bias"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["switch", "change providers", "migrate", "relearn", "setup"],
  },

  // ───────────────────────── Probability & risk ─────────────────────────
  {
    id: "expected-value",
    name: "Expected Value",
    aliases: ["EV"],
    domain: "probability",
    originator: "von Neumann & Morgenstern; classical decision theory",
    primarySource: "Theory of Games and Economic Behavior (1944)",
    oneLine: "Weigh each outcome by how likely it is, not by how vivid or scary it feels.",
    whenToUse: [
      "You have named options, real uncertainty on both, and payoffs you can roughly size.",
      "Best when no single downside would be truly ruinous.",
    ],
    whenItMisleads: [
      "It treats a bad-outcome probability as survivable arithmetic — if the downside would be ruinous rather than merely unpleasant, this is the wrong lens.",
    ],
    decisionTypes: ["binary", "risk", "multi-option"],
    relatedModels: ["base-rates", "kelly-criterion"],
    contradicts: ["loss-aversion", "black-swan-tail-risk"],
    visualTemplate: "decision-tree",
    keywords: ["chance", "probability", "likely", "payoff", "odds", "risk"],
  },
  {
    id: "base-rates",
    name: "Base Rates",
    aliases: ["base rate neglect (inverse)"],
    domain: "probability",
    originator: "Daniel Kahneman & Amos Tversky",
    primarySource: "Judgment under Uncertainty (1974)",
    oneLine: "Start from how often this kind of outcome happens in general, then adjust for what's specific to you.",
    whenToUse: [
      "You're estimating a probability mostly from your own story rather than from how things usually go.",
      "Useful whenever you have (or could look up) a reference class.",
    ],
    whenItMisleads: [
      "A base rate can be irrelevant if your situation is genuinely structurally different from the reference class.",
    ],
    decisionTypes: ["risk", "binary"],
    relatedModels: ["expected-value"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["usually", "on average", "most people", "typical", "odds are"],
  },
  {
    id: "black-swan-tail-risk",
    name: "Black Swan / Tail Risk",
    aliases: ["fat-tailed risk"],
    domain: "probability",
    originator: "Nassim Nicholas Taleb",
    primarySource: "The Black Swan (2007)",
    oneLine: "Rare, extreme events matter more than their small probability suggests, because average-case math can't price them.",
    whenToUse: [
      "One branch of the decision has a low-probability outcome that would be catastrophic or irreversible.",
      "Useful as a check on any purely expected-value calculation.",
    ],
    whenItMisleads: [
      "Overweighting tail risk in genuinely low-stakes, reversible decisions creates needless paralysis.",
    ],
    decisionTypes: ["risk"],
    stakesFit: ["high"],
    relatedModels: ["margin-of-safety", "antifragility"],
    contradicts: ["expected-value"],
    visualTemplate: "narrative",
    keywords: ["catastrophic", "ruin", "worst case", "irreversible", "extreme"],
  },
  {
    id: "antifragility",
    name: "Antifragility",
    aliases: ["hormesis (biological framing)"],
    domain: "probability",
    originator: "Nassim Nicholas Taleb",
    primarySource: "Antifragile (2012)",
    oneLine: "Some options gain from disorder and volatility rather than merely surviving it — look for that asymmetry.",
    whenToUse: [
      "One path has capped downside and open-ended upside, or gets stronger the more it's stress-tested.",
      "Useful for comparing options by their shape, not just their expected outcome.",
    ],
    whenItMisleads: [
      "Not every volatile option is antifragile — check the downside is genuinely capped before leaning on this.",
    ],
    decisionTypes: ["risk", "resource-allocation"],
    relatedModels: ["black-swan-tail-risk"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["upside", "optionality", "volatile", "stress test", "bet"],
  },
  {
    id: "bayesian-updating",
    name: "Bayesian Updating",
    aliases: ["Bayes' theorem"],
    domain: "probability",
    originator: "Thomas Bayes; Pierre-Simon Laplace",
    primarySource: "An Essay towards solving a Problem in the Doctrine of Chances (1763)",
    oneLine: "Start from your prior belief, then shift it by exactly as much as the new evidence actually warrants.",
    whenToUse: [
      "New information has arrived since you first formed your view on this decision.",
      "Useful for checking you're updating proportionally, not overreacting to the latest data point.",
    ],
    whenItMisleads: [
      "It requires an honest prior — if your starting belief was already motivated reasoning, the update inherits that bias.",
    ],
    decisionTypes: ["risk", "binary"],
    relatedModels: ["base-rates"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["new information", "changed my mind", "updated", "evidence", "learned"],
  },
  {
    id: "kelly-criterion",
    name: "Kelly Criterion",
    aliases: ["optimal bet sizing"],
    domain: "probability",
    originator: "John L. Kelly Jr.",
    primarySource: "A New Interpretation of Information Rate (1956)",
    oneLine: "Size your commitment to your edge — betting more than your real edge justifies ruins you faster than betting too little.",
    whenToUse: [
      "The decision is really about how much to commit (money, time, effort), not just whether to commit at all.",
      "Useful whenever you can estimate your real edge and the size of the downside.",
    ],
    whenItMisleads: [
      "It assumes you can estimate your edge accurately — a wrong estimate produces a confidently wrong bet size.",
    ],
    decisionTypes: ["resource-allocation", "risk"],
    relatedModels: ["expected-value", "margin-of-safety"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["how much", "bet size", "commit", "invest", "allocate"],
  },

  // ───────────────────────── Systems & feedback ─────────────────────────
  {
    id: "feedback-loops",
    name: "Feedback Loops",
    aliases: ["reinforcing and balancing loops"],
    domain: "systems",
    originator: "Jay Forrester; Donella Meadows",
    primarySource: "Thinking in Systems (2008)",
    oneLine: "Some effects reinforce themselves (they compound) and some balance themselves out (they self-correct) — know which kind you're triggering.",
    whenToUse: [
      "The outcome of this decision will feed back into the situation that produced it, rather than being a one-off event.",
      "Useful for spotting compounding effects before they run away from you.",
    ],
    whenItMisleads: [
      "Not every effect loops — sometimes a decision really is a clean, one-time event with no feedback to trace.",
    ],
    decisionTypes: ["timing", "resource-allocation", "binary"],
    relatedModels: ["second-order-thinking", "tipping-points"],
    contradicts: [],
    visualTemplate: "feedback-loop",
    keywords: ["compounds", "spirals", "cycle", "self-reinforcing", "snowball"],
  },
  {
    id: "second-order-thinking",
    name: "Second-Order Thinking",
    aliases: ["third-order thinking"],
    domain: "systems",
    originator: "Popularised by Howard Marks; Donella Meadows' systems tradition",
    primarySource: "The Most Important Thing (2011)",
    oneLine: "Ask what happens next, and then what happens after that — not just the immediate, visible effect.",
    whenToUse: [
      "The decision has a long consequence chain and the costs likely sit two or three steps out, not in the first move.",
      "Useful whenever the obvious effect is the one everyone's already discussing.",
    ],
    whenItMisleads: [
      "Chains can be extended indefinitely until every option looks bad — stop at the order where you could still act differently.",
    ],
    decisionTypes: ["binary", "multi-option", "timing"],
    stakesFit: ["medium", "high"],
    relatedModels: ["feedback-loops"],
    contradicts: ["present-bias"],
    visualTemplate: "consequence-chain",
    keywords: ["long-term", "consequences", "ripple", "down the line", "later on"],
  },
  {
    id: "chestertons-fence",
    name: "Chesterton's Fence",
    aliases: [],
    domain: "systems",
    originator: "G. K. Chesterton",
    primarySource: "The Thing (1929)",
    oneLine: "Don't remove or change something until you understand why it's there in the first place.",
    whenToUse: [
      "You're tempted to tear down a process, rule, or relationship that seems to serve no obvious purpose.",
      "Useful before any 'this is obviously pointless, let's cut it' decision.",
    ],
    whenItMisleads: [
      "It can be used to defend anything indefinitely — 'someone must have had a reason' isn't proof the reason still applies.",
    ],
    decisionTypes: ["binary", "values-conflict"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["remove", "get rid of", "why does this exist", "pointless", "tradition"],
  },
  {
    id: "tipping-points",
    name: "Tipping Points",
    aliases: ["critical mass"],
    domain: "systems",
    originator: "Thomas Schelling; popularised by Malcolm Gladwell",
    primarySource: "Micromotives and Macrobehavior (1978)",
    oneLine: "Some systems change gradually, then suddenly, once a threshold is crossed — small pushes near that line matter a lot.",
    whenToUse: [
      "The decision is about timing a push on something that's been slow to move.",
      "Useful for deciding whether you're near a threshold worth one more push, or far from it.",
    ],
    whenItMisleads: [
      "It's easy to convince yourself you're 'almost at the tipping point' indefinitely — check for real evidence, not hope.",
    ],
    decisionTypes: ["timing", "resource-allocation"],
    relatedModels: ["feedback-loops"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["momentum", "almost there", "threshold", "push", "traction"],
  },
  {
    id: "theory-of-constraints",
    name: "Theory of Constraints",
    aliases: ["bottleneck thinking"],
    domain: "systems",
    originator: "Eliyahu M. Goldratt",
    primarySource: "The Goal (1984)",
    oneLine: "A system's output is capped by its single tightest bottleneck — fixing anything else barely moves the result.",
    whenToUse: [
      "You're deciding where to spend limited effort across several parts of a process.",
      "Useful for checking you're not improving something that was never the real limiter.",
    ],
    whenItMisleads: [
      "The bottleneck can move once you fix the current one — don't assume one fix solves it permanently.",
    ],
    decisionTypes: ["resource-allocation"],
    relatedModels: ["diminishing-returns"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["bottleneck", "slowest part", "limiting factor", "stuck", "throughput"],
  },
  {
    id: "goodharts-law",
    name: "Goodhart's Law",
    aliases: [],
    domain: "systems",
    originator: "Charles Goodhart",
    primarySource: "Monetary Theory and Practice (1984)",
    oneLine: "Once a measure becomes the target, people optimise the measure instead of the thing it was meant to represent.",
    whenToUse: [
      "The decision involves setting or chasing a metric, quota, or KPI.",
      "Useful for checking whether hitting the number still means what it originally meant.",
    ],
    whenItMisleads: [
      "Not every metric gets gamed — simple, hard-to-fake measures can stay honest indicators for a long time.",
    ],
    decisionTypes: ["resource-allocation", "multi-option"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["metric", "target", "quota", "kpi", "score", "numbers"],
  },

  // ───────────────────────── Strategy & game theory ─────────────────────────
  {
    id: "nash-equilibrium",
    name: "Nash Equilibrium",
    aliases: [],
    domain: "strategy",
    originator: "John Nash",
    primarySource: "Non-Cooperative Games (1950)",
    oneLine: "A stable outcome is one where no side can do better by changing their move alone — check whether your plan assumes the other side stays still.",
    whenToUse: [
      "Another party's likely response matters as much as your own move.",
      "Useful for checking a plan that only works if the other side doesn't react.",
    ],
    whenItMisleads: [
      "Real people aren't always rational optimisers — don't over-model a relationship as a cold game.",
    ],
    decisionTypes: ["negotiation", "multi-option"],
    relatedModels: ["zero-sum-vs-positive-sum"],
    contradicts: ["principled-negotiation"],
    visualTemplate: "narrative",
    keywords: ["their response", "counter", "competitor", "other side", "react"],
  },
  {
    id: "zero-sum-vs-positive-sum",
    name: "Zero-Sum vs. Positive-Sum",
    aliases: [],
    domain: "strategy",
    originator: "Game theory; popularised in negotiation literature",
    primarySource: "Theory of Games and Economic Behavior (1944)",
    oneLine: "Check whether this is really a fixed pie to split, or whether both sides could end up better off.",
    whenToUse: [
      "You're framing a negotiation or conflict as purely win/lose before checking if that's actually true.",
      "Useful right before you decide how hard to push versus how much to collaborate.",
    ],
    whenItMisleads: [
      "Some situations really are zero-sum — treating a genuine conflict as win-win can just mean you lose politely.",
    ],
    decisionTypes: ["negotiation", "values-conflict"],
    relatedModels: ["nash-equilibrium", "principled-negotiation"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["win-win", "split", "compete", "fixed pie", "both sides"],
  },
  {
    id: "ooda-loop",
    name: "OODA Loop",
    aliases: ["observe-orient-decide-act"],
    domain: "strategy",
    originator: "John Boyd",
    primarySource: "Patterns of Conflict (1976)",
    oneLine: "Whoever cycles through observe → orient → decide → act fastest usually shapes how the situation unfolds.",
    whenToUse: [
      "The situation is moving and being fast-but-good beats being slow-but-perfect.",
      "Useful when you're deciding how long to keep gathering information before acting.",
    ],
    whenItMisleads: [
      "Speed without real orientation just means making the same mistake faster.",
    ],
    decisionTypes: ["timing", "risk"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["fast", "move quickly", "competitor", "react", "tempo"],
  },
  {
    id: "suntzu-principles",
    name: "Know Yourself, Know the Situation",
    aliases: ["Sun Tzu's principles"],
    domain: "strategy",
    originator: "Sun Tzu",
    primarySource: "The Art of War (5th century BC), summarised in original language",
    oneLine: "Clear-eyed self-assessment plus a clear read on the terrain beats cleverness applied to a fuzzy picture of either.",
    whenToUse: [
      "You suspect the plan is more polished than your understanding of your own constraints or the real situation.",
      "Useful as a check before committing to an ambitious move.",
    ],
    whenItMisleads: [
      "Self-assessment can tip into over-caution — perfect information is never available before acting.",
    ],
    decisionTypes: ["binary", "risk"],
    relatedModels: ["circle-of-competence"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["prepared", "understand the situation", "know myself", "assess"],
  },
  {
    id: "schelling-point",
    name: "Schelling Point",
    aliases: ["focal point"],
    domain: "strategy",
    originator: "Thomas Schelling",
    primarySource: "The Strategy of Conflict (1960)",
    oneLine: "Without communication, people tend to converge on the option that's obvious, salient, or default — that's worth naming out loud.",
    whenToUse: [
      "Multiple parties need to coordinate without much back-and-forth negotiation.",
      "Useful for spotting the 'obvious' answer everyone will land on anyway.",
    ],
    whenItMisleads: [
      "The obvious choice isn't always the best one — it's just the one that's easiest to coordinate around.",
    ],
    decisionTypes: ["negotiation", "multi-option"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["coordinate", "obvious choice", "default", "everyone agrees"],
  },
  {
    id: "minimax-maximin",
    name: "Minimax / Maximin",
    aliases: [],
    domain: "strategy",
    originator: "John von Neumann",
    primarySource: "Zur Theorie der Gesellschaftsspiele (1928)",
    oneLine: "Pick the option whose worst-case outcome is the least bad, rather than the one with the best best-case.",
    whenToUse: [
      "You care more about avoiding a terrible outcome than maximising a great one.",
      "Useful for comparing options by their floor, not their ceiling.",
    ],
    whenItMisleads: [
      "Always optimising for the worst case can leave real upside on the table when the worst case is genuinely unlikely.",
    ],
    decisionTypes: ["risk", "multi-option"],
    relatedModels: ["expected-value"],
    contradicts: ["expected-value"],
    visualTemplate: "narrative",
    keywords: ["worst case", "safest option", "floor", "guaranteed"],
  },

  // ───────────────────────── Philosophy & first principles ─────────────────────────
  {
    id: "inversion",
    name: "Inversion",
    aliases: ["invert, always invert"],
    domain: "philosophy",
    originator: "Carl Jacobi; popularised by Charlie Munger",
    primarySource: "Munger's Poor Charlie's Almanack (2005)",
    oneLine: "Instead of asking how to succeed, ask what would guarantee failure — then avoid that.",
    whenToUse: [
      "The forward version of the question feels vague or you're stuck on what to optimise for.",
      "Useful as a first move on almost any hard decision.",
    ],
    whenItMisleads: [
      "Avoiding every failure mode can leave you with an overly defensive, opportunity-less choice.",
    ],
    decisionTypes: ["binary", "multi-option", "values-conflict"],
    relatedModels: ["pre-mortem"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["fail", "go wrong", "avoid", "worst outcome", "backwards"],
  },
  {
    id: "occams-razor",
    name: "Occam's Razor",
    aliases: ["Ockham's razor"],
    domain: "philosophy",
    originator: "William of Ockham",
    primarySource: "Medieval scholastic philosophy",
    oneLine: "Among explanations or plans that fit the facts equally well, prefer the simplest one.",
    whenToUse: [
      "You're weighing a simple, direct option against an elaborate one that only wins under extra assumptions.",
      "Useful for cutting through an overcomplicated plan.",
    ],
    whenItMisleads: [
      "Simple isn't the same as correct — some real situations genuinely need a complicated answer.",
    ],
    decisionTypes: ["binary", "multi-option"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["simple", "complicated", "overthinking", "straightforward"],
  },
  {
    id: "hanlons-razor",
    name: "Hanlon's Razor",
    aliases: [],
    domain: "philosophy",
    originator: "Attributed to Robert J. Hanlon",
    primarySource: "Popularised through the Jargon File (1990)",
    oneLine: "Don't assume bad intent when carelessness, ignorance, or a bad process explains the situation just as well.",
    whenToUse: [
      "The decision is being driven by how you're reading someone else's motives.",
      "Useful before reacting to something that felt like a slight.",
    ],
    whenItMisleads: [
      "Sometimes intent really is malicious — this isn't a reason to ignore a genuine pattern of bad faith.",
    ],
    decisionTypes: ["values-conflict", "negotiation"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["intentional", "on purpose", "betrayed", "motives", "why did they"],
  },
  {
    id: "dichotomy-of-control",
    name: "Dichotomy of Control",
    aliases: [],
    domain: "philosophy",
    originator: "Epictetus",
    primarySource: "The Enchiridion (1st century AD), summarised in original language",
    oneLine: "Separate what you can actually influence from what you can only respond to, and spend your energy on the first pile.",
    whenToUse: [
      "Part of what's weighing on the decision is genuinely outside your control.",
      "Useful for narrowing an overwhelming decision down to the part that's actually yours to make.",
    ],
    whenItMisleads: [
      "It can tip into passivity — some things that feel uncontrollable are actually influenceable with enough effort.",
    ],
    decisionTypes: ["values-conflict", "binary"],
    relatedModels: ["circle-of-control-concern"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["out of my control", "can't control", "depends on", "up to them"],
  },
  {
    id: "first-principles-thinking",
    name: "First-Principles Thinking",
    aliases: [],
    domain: "philosophy",
    originator: "Aristotle; popularised in modern form by Elon Musk",
    primarySource: "Aristotle's Physics; modern usage in engineering and strategy",
    oneLine: "Break the decision down to the basic facts you're sure of, then rebuild a plan from there instead of from analogy.",
    whenToUse: [
      "You notice you're deciding 'the way it's usually done' rather than from the actual constraints of your situation.",
      "Useful when convention and your specific situation might not actually match.",
    ],
    whenItMisleads: [
      "Rebuilding from scratch is slow — for low-stakes, well-understood decisions, borrowing convention is usually fine.",
    ],
    decisionTypes: ["binary", "multi-option"],
    relatedModels: ["occams-razor"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["usually done", "convention", "from scratch", "assumptions"],
  },
  {
    id: "via-negativa",
    name: "Via Negativa",
    aliases: [],
    domain: "philosophy",
    originator: "Negative theology tradition; popularised by Nassim Taleb",
    primarySource: "Antifragile (2012)",
    oneLine: "Improvement often comes faster from removing what's harmful than from adding something new.",
    whenToUse: [
      "You're tempted to solve a problem by adding more (more effort, more features, more commitments).",
      "Useful for asking what you could simply stop doing instead.",
    ],
    whenItMisleads: [
      "Sometimes the honest answer really does require adding something new, not just subtracting.",
    ],
    decisionTypes: ["multi-option", "resource-allocation"],
    relatedModels: ["inversion"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["remove", "stop doing", "simplify", "cut back", "subtract"],
  },

  // ───────────────────────── Decision structuring ─────────────────────────
  {
    id: "eisenhower-matrix",
    name: "Eisenhower Matrix",
    aliases: ["urgent-important matrix"],
    domain: "structuring",
    originator: "Attributed to Dwight D. Eisenhower",
    primarySource: "Popularised by Stephen Covey, The 7 Habits (1989)",
    oneLine: "Sort by urgency and importance separately — what's loud isn't always what matters most.",
    whenToUse: [
      "You're deciding what to prioritise among several competing demands.",
      "Useful whenever 'urgent' and 'important' are being treated as the same thing.",
    ],
    whenItMisleads: [
      "It's a sorting tool, not a strategy — it won't tell you whether something belongs on the list at all.",
    ],
    decisionTypes: ["resource-allocation", "multi-option"],
    relatedModels: ["theory-of-constraints"],
    contradicts: [],
    visualTemplate: "two-by-two",
    keywords: ["urgent", "important", "prioritise", "deadline pressure"],
  },
  {
    id: "pre-mortem",
    name: "Pre-Mortem",
    aliases: [],
    domain: "structuring",
    originator: "Gary Klein",
    primarySource: "Performing a Project Premortem, HBR (2007)",
    oneLine: "Imagine the decision has already failed a year from now, then work backwards to find out why.",
    whenToUse: [
      "Before committing to a plan you're already fairly excited about.",
      "Useful for surfacing risks that optimism is currently hiding.",
    ],
    whenItMisleads: [
      "A pre-mortem that turns into pure pessimism can talk you out of a genuinely good bet.",
    ],
    decisionTypes: ["binary", "risk"],
    relatedModels: ["inversion"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["what could go wrong", "risks", "before committing", "plan fails"],
  },
  {
    id: "ten-ten-ten-rule",
    name: "10-10-10 Rule",
    aliases: [],
    domain: "structuring",
    originator: "Suzy Welch",
    primarySource: "10-10-10: A Life-Transforming Idea (2009)",
    oneLine: "Ask how you'll feel about this choice in 10 minutes, 10 months, and 10 years — the three answers rarely agree.",
    whenToUse: [
      "The decision has a strong emotional pull right now that might not reflect how it looks later.",
      "Useful whenever present feelings and long-term consequences might be pointing different directions.",
    ],
    whenItMisleads: [
      "Predicting your future feelings is unreliable — treat the 10-year answer as a useful prompt, not a certainty.",
    ],
    decisionTypes: ["binary", "timing", "values-conflict"],
    relatedModels: ["present-bias"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["emotional", "feel right now", "later", "years from now"],
  },
  {
    id: "regret-minimization",
    name: "Regret Minimisation Framework",
    aliases: [],
    domain: "structuring",
    originator: "Jeff Bezos; regret theory (Loomes & Sugden)",
    primarySource: "1997 Amazon founding rationale; Loomes & Sugden (1982)",
    oneLine: "Project yourself forward and ask which choice you'd regret not having made.",
    whenToUse: [
      "The stakes are high, the decision is rare, and there's a real emotional pull in how you describe it.",
      "Useful when payoff-based reasoning alone feels like it's missing something.",
    ],
    whenItMisleads: [
      "Anticipated regret is systematically overestimated — people adapt to both outcomes faster than they expect.",
    ],
    decisionTypes: ["binary", "values-conflict"],
    stakesFit: ["high"],
    relatedModels: ["ten-ten-ten-rule"],
    contradicts: ["expected-value"],
    visualTemplate: "two-by-two",
    keywords: ["regret", "wonder what if", "once in a lifetime", "look back"],
  },
  {
    id: "weighted-decision-matrix",
    name: "Weighted Decision Matrix",
    aliases: ["Franklin's moral algebra"],
    domain: "structuring",
    originator: "Multi-criteria decision analysis; Benjamin Franklin's moral algebra",
    primarySource: "Franklin's 1772 letter to Joseph Priestley",
    oneLine: "Name what actually matters, weight it honestly, then score each option against it.",
    whenToUse: [
      "The decision mixes several different kinds of value (money, time, relationships, risk) in one sentence.",
      "Useful for separating those factors before comparing options.",
    ],
    whenItMisleads: [
      "The weights are a mirror, not a measurement — it's easy to tune them until they produce the answer you already wanted.",
    ],
    decisionTypes: ["multi-option", "binary", "resource-allocation"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "weighted-scorecard",
    keywords: ["weigh", "criteria", "matters most", "compare options", "factors"],
  },
  {
    id: "two-way-vs-one-way-door",
    name: "Two-Way vs. One-Way Door",
    aliases: ["reversibility framework"],
    domain: "structuring",
    originator: "Jeff Bezos",
    primarySource: "2016 letter to Amazon shareholders",
    oneLine: "Decide fast on choices you can reverse; slow down only for the ones you genuinely can't undo.",
    whenToUse: [
      "You're not sure how much deliberation this decision actually deserves.",
      "Useful as the very first question before anything else.",
    ],
    whenItMisleads: [
      "Almost nothing is perfectly one-way or two-way — most decisions sit somewhere on a spectrum of how hard they'd be to undo.",
    ],
    decisionTypes: ["binary", "timing"],
    relatedModels: ["status-quo-bias"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["reversible", "undo", "permanent", "can't take it back"],
  },

  // ───────────────────────── Negotiation & influence ─────────────────────────
  {
    id: "batna",
    name: "BATNA",
    aliases: ["best alternative to a negotiated agreement"],
    domain: "negotiation",
    originator: "Roger Fisher & William Ury",
    primarySource: "Getting to Yes (1981)",
    oneLine: "Your real negotiating power is the strength of what you'll do if this deal falls through.",
    whenToUse: [
      "You're deciding whether to accept, counter, or walk away from an offer.",
      "Useful for checking whether you actually know your own walk-away option.",
    ],
    whenItMisleads: [
      "An untested or imagined BATNA can make you overconfident about walking away.",
    ],
    decisionTypes: ["negotiation"],
    relatedModels: ["zopa"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["offer", "counter", "walk away", "deal", "alternative option"],
  },
  {
    id: "zopa",
    name: "ZOPA",
    aliases: ["zone of possible agreement"],
    domain: "negotiation",
    originator: "Negotiation theory, following Fisher & Ury",
    primarySource: "Getting to Yes (1981)",
    oneLine: "There's only a deal if the ranges each side would accept actually overlap — check that before you negotiate the details.",
    whenToUse: [
      "Two sides are still far apart and you're not sure a deal is even possible in principle.",
      "Useful before investing more time in negotiating specifics.",
    ],
    whenItMisleads: [
      "A ZOPA that looks non-existent today can open up once non-price terms are added to the table.",
    ],
    decisionTypes: ["negotiation"],
    relatedModels: ["batna"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["deal range", "acceptable", "overlap", "negotiate"],
  },
  {
    id: "anchoring-in-negotiation",
    name: "Anchoring in Negotiation",
    aliases: [],
    domain: "negotiation",
    originator: "Adam Galinsky & Thomas Mussweiler",
    primarySource: "First Offers as Anchors (2001)",
    oneLine: "Whoever names a credible number first tends to pull the eventual outcome toward it.",
    whenToUse: [
      "You're deciding whether to make the first offer or wait for the other side to name a number.",
      "Useful for deciding how aggressive your opening number should be.",
    ],
    whenItMisleads: [
      "An anchor with no credible justification behind it can backfire and damage trust in the negotiation.",
    ],
    decisionTypes: ["negotiation"],
    relatedModels: ["anchoring-bias"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["first offer", "opening number", "counter-offer"],
  },
  {
    id: "reciprocity-principle",
    name: "Reciprocity Principle",
    aliases: [],
    domain: "negotiation",
    originator: "Robert Cialdini",
    primarySource: "Influence (1984)",
    oneLine: "People feel obliged to return a favour, a concession, or information given to them — including you.",
    whenToUse: [
      "You're deciding whether a small concession now might move the whole negotiation or relationship forward.",
      "Useful for noticing when you're the one who feels obligated to reciprocate.",
    ],
    whenItMisleads: [
      "Reciprocity can be exploited deliberately — a manufactured favour isn't a real reason to concede something big.",
    ],
    decisionTypes: ["negotiation", "values-conflict"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["favour", "concession", "owe them", "give and take"],
  },
  {
    id: "social-proof",
    name: "Social Proof",
    aliases: [],
    domain: "negotiation",
    originator: "Robert Cialdini",
    primarySource: "Influence (1984)",
    oneLine: "We look to what similar others are doing as a signal for what's correct, especially under uncertainty.",
    whenToUse: [
      "Part of what's pulling you toward an option is that 'everyone else is doing it.'",
      "Useful for separating that signal from the option's actual merits for you.",
    ],
    whenItMisleads: [
      "A crowd can be wrong together just as easily as it can be right — popularity isn't evidence of fit.",
    ],
    decisionTypes: ["binary", "values-conflict"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["everyone else", "popular", "trend", "what others do"],
  },
  {
    id: "principled-negotiation",
    name: "Principled Negotiation",
    aliases: ["separate people from the problem"],
    domain: "negotiation",
    originator: "Roger Fisher & William Ury",
    primarySource: "Getting to Yes (1981)",
    oneLine: "Focus on each side's underlying interests, not their stated positions, and keep the relationship separate from the issue.",
    whenToUse: [
      "The negotiation is getting personal, or both sides seem locked into positions rather than goals.",
      "Useful for finding a deal neither side's opening position actually proposed.",
    ],
    whenItMisleads: [
      "It assumes good faith on both sides — it won't help against a counterpart negotiating purely adversarially.",
    ],
    decisionTypes: ["negotiation", "values-conflict"],
    relatedModels: ["zero-sum-vs-positive-sum"],
    contradicts: ["nash-equilibrium"],
    visualTemplate: "narrative",
    keywords: ["interests", "positions", "relationship", "underlying reason"],
  },

  // ───────────────────────── Management & business strategy ─────────────────────────
  {
    id: "swot-analysis",
    name: "SWOT Analysis",
    aliases: [],
    domain: "management",
    originator: "Albert Humphrey and colleagues, Stanford Research Institute",
    primarySource: "1960s–70s SRI research",
    oneLine: "Lay out strengths, weaknesses, opportunities, and threats side by side before committing to a direction.",
    whenToUse: [
      "You want a structured first pass over a decision that mixes internal factors and external conditions.",
      "Useful as a starting scaffold, not a final answer.",
    ],
    whenItMisleads: [
      "It's easy to fill the boxes and never actually rank or weigh what's inside them — a list isn't a decision.",
    ],
    decisionTypes: ["multi-option", "binary"],
    relatedModels: ["weighted-decision-matrix"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["strengths", "weaknesses", "opportunities", "threats"],
  },
  {
    id: "jobs-to-be-done",
    name: "Jobs-to-Be-Done",
    aliases: [],
    domain: "management",
    originator: "Clayton Christensen",
    primarySource: "Competing Against Luck (2016)",
    oneLine: "People don't want a thing, they want the progress that thing lets them make — find the real job before choosing.",
    whenToUse: [
      "You're deciding between options and it's worth double-checking what underlying need you're actually solving for.",
      "Useful for reframing a decision that feels stuck between two similar-looking choices.",
    ],
    whenItMisleads: [
      "Stated jobs can mask a different, unstated one — this only helps if you're honest about the real motivation.",
    ],
    decisionTypes: ["multi-option", "binary"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["what I actually need", "real reason", "underlying need", "purpose"],
  },
  {
    id: "cynefin-framework",
    name: "Cynefin Framework",
    aliases: [],
    domain: "management",
    originator: "Dave Snowden",
    primarySource: "A Leader's Framework for Decision Making, HBR (2007)",
    oneLine: "Match your approach to the situation's real complexity — simple, complicated, complex, or chaotic each call for a different way of deciding.",
    whenToUse: [
      "You're not sure whether this decision has a knowable right answer or needs to be probed through experiments.",
      "Useful for choosing between 'analyse carefully' and 'try something small and see what happens.'",
    ],
    whenItMisleads: [
      "Misclassifying a genuinely simple decision as complex adds needless process and delay.",
    ],
    decisionTypes: ["multi-option", "risk"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["complex", "uncertain", "experiment", "unclear", "unpredictable"],
  },
  {
    id: "moat-thinking",
    name: "Moat Thinking",
    aliases: ["economic moats"],
    domain: "management",
    originator: "Warren Buffett",
    primarySource: "Berkshire Hathaway shareholder letters",
    oneLine: "Ask what durable advantage protects this choice from being copied, undercut, or eroded over time.",
    whenToUse: [
      "You're deciding whether an advantage is a real, structural edge or just a temporary lead.",
      "Useful before committing resources to something others could easily replicate.",
    ],
    whenItMisleads: [
      "Overrating your own moat is a common failure mode — competitors close gaps faster than owners expect.",
    ],
    decisionTypes: ["resource-allocation", "risk"],
    relatedModels: ["circle-of-competence"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["advantage", "defensible", "copy", "compete away", "durable"],
  },
  {
    id: "mece-principle",
    name: "MECE Principle",
    aliases: ["mutually exclusive, collectively exhaustive"],
    domain: "management",
    originator: "Barbara Minto, McKinsey & Company",
    primarySource: "The Pyramid Principle (1987)",
    oneLine: "Break the decision into parts that don't overlap and together cover the whole problem — half-formed categories hide gaps.",
    whenToUse: [
      "The option list feels muddled, with categories that overlap or clearly miss something.",
      "Useful for cleaning up the option set before comparing anything.",
    ],
    whenItMisleads: [
      "Forcing a messy, genuinely fuzzy situation into clean categories can hide real overlap that matters.",
    ],
    decisionTypes: ["multi-option"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["categories", "overlap", "missing something", "structure the options"],
  },
  {
    id: "build-measure-learn",
    name: "Build-Measure-Learn",
    aliases: ["Lean Startup loop"],
    domain: "management",
    originator: "Eric Ries",
    primarySource: "The Lean Startup (2011)",
    oneLine: "When you're unsure, commit to the smallest real test that produces a genuine answer, rather than a big bet on a guess.",
    whenToUse: [
      "You're deciding between committing fully now versus running a smaller test first.",
      "Useful whenever the biggest uncertainty could be resolved by real-world data rather than more analysis.",
    ],
    whenItMisleads: [
      "Some decisions genuinely can't be tested small — a partial pilot can also give a misleadingly clean signal.",
    ],
    decisionTypes: ["timing", "risk", "resource-allocation"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["test first", "pilot", "small experiment", "before committing fully"],
  },

  // ───────────────────────── Personal decision & productivity ─────────────────────────
  {
    id: "values-based-filtering",
    name: "Values-Based Filtering",
    aliases: [],
    domain: "personal",
    originator: "Common in personal-decision coaching practice",
    primarySource: "Applied ethics and coaching literature",
    oneLine: "Name your two or three non-negotiable values first, then check which option actually honours them.",
    whenToUse: [
      "The decision feels emotionally loaded in a way that pure numbers don't capture.",
      "Useful when every option scores similarly on the practical metrics.",
    ],
    whenItMisleads: [
      "Values can conflict with each other — this doesn't resolve the tie, it just makes the real trade-off explicit.",
    ],
    decisionTypes: ["values-conflict", "binary"],
    relatedModels: ["dichotomy-of-control"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["what matters to me", "values", "principles", "feels right"],
  },
  {
    id: "circle-of-control-concern",
    name: "Circle of Control / Circle of Concern",
    aliases: [],
    domain: "personal",
    originator: "Stephen Covey",
    primarySource: "The 7 Habits of Highly Effective People (1989)",
    oneLine: "Separate what genuinely worries you from what you can actually act on, and focus effort inside that smaller circle.",
    whenToUse: [
      "A lot of the anxiety around this decision is about things you can't directly change.",
      "Useful for narrowing an overwhelming decision to its actionable core.",
    ],
    whenItMisleads: [
      "The circle of control is usually a bit bigger than it first feels — don't use this to give up on things you could still influence.",
    ],
    decisionTypes: ["values-conflict", "binary"],
    relatedModels: ["dichotomy-of-control"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["worried about", "out of my hands", "anxious", "can't change"],
  },
  {
    id: "five-whys",
    name: "Five Whys",
    aliases: ["root cause analysis"],
    domain: "personal",
    originator: "Sakichi Toyoda; formalised at Toyota",
    primarySource: "Toyota Production System",
    oneLine: "Ask 'why' repeatedly on the stated problem until you hit the actual root cause instead of its surface symptom.",
    whenToUse: [
      "The decision is a response to a recurring problem rather than a one-off event.",
      "Useful for checking you're solving the real problem, not just its latest symptom.",
    ],
    whenItMisleads: [
      "Root causes are sometimes genuinely multiple, not a single neat chain — don't force one linear answer.",
    ],
    decisionTypes: ["binary", "multi-option"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "consequence-chain",
    keywords: ["keeps happening", "recurring problem", "root cause", "why does this keep"],
  },
  {
    id: "satisficing-vs-maximizing",
    name: "Satisficing vs. Maximising",
    aliases: [],
    domain: "personal",
    originator: "Herbert Simon",
    primarySource: "Models of Man (1957)",
    oneLine: "Decide upfront whether you're looking for 'good enough that clears the bar' or 'provably the best' — the second one costs far more time for often marginal gain.",
    whenToUse: [
      "You're stuck comparing many similar options and the search itself is costing you more than the difference between them.",
      "Useful for consciously choosing your standard before you start comparing.",
    ],
    whenItMisleads: [
      "For a genuinely rare, high-stakes, irreversible decision, maximising the extra effort can be worth it.",
    ],
    decisionTypes: ["multi-option"],
    relatedModels: ["paradox-of-choice"],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["good enough", "best option", "keep searching", "settle"],
  },
  {
    id: "energy-vs-time-management",
    name: "Energy Management vs. Time Management",
    aliases: [],
    domain: "personal",
    originator: "Jim Loehr & Tony Schwartz",
    primarySource: "The Power of Full Engagement (2003)",
    oneLine: "The scarce resource is often your energy and attention, not the raw hours on the clock — plan around that instead.",
    whenToUse: [
      "You're deciding how to schedule or sequence something, not just whether to do it.",
      "Useful when 'I don't have time' might actually mean 'I don't have the energy at that time.'",
    ],
    whenItMisleads: [
      "Some genuinely are pure time-scarcity problems — don't reframe a real capacity shortfall as an energy issue.",
    ],
    decisionTypes: ["timing", "resource-allocation"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["exhausted", "no time", "when to do it", "schedule", "energy"],
  },
  {
    id: "decision-journaling",
    name: "Decision Journaling",
    aliases: ["calibration tracking"],
    domain: "personal",
    originator: "Popularised by Michael Mauboussin and Annie Duke",
    primarySource: "Thinking in Bets (2018)",
    oneLine: "Write down what you expect and why before the outcome is known, so you can honestly check your calibration later.",
    whenToUse: [
      "This is the kind of decision you'll likely face again in some form, and getting better at it matters.",
      "Useful for separating a good decision from a good outcome after the fact.",
    ],
    whenItMisleads: [
      "It only pays off over many decisions — treating any single journal entry as proof of skill is premature.",
    ],
    decisionTypes: ["binary", "risk"],
    relatedModels: [],
    contradicts: [],
    visualTemplate: "narrative",
    keywords: ["log this", "track", "look back later", "was I right"],
  },
];
